# https://taskfile.dev
version: '3'

dotenv:
  - .env

tasks:
  default:
    aliases: ["all"]
    cmds:
      - task: up
      - task: unseal

  up:
    preconditions:
      - test -f .env
      - test -f docker-compose.yml
    cmds:
      - docker compose up -d --pull=missing
      - sleep 5
      - |
        echo "Grafana: http://localhost:3000"
        echo "Prometheus: http://localhost:9090"
        echo "Vault: http://localhost:8200"
    silent: true

  vault-up:
    preconditions:
      - test -f .env
      - test -f docker-compose.yml
    cmds:
      - docker compose up vault -d --pull=missing
      - sleep 5
      - |
        echo "Vault: http://localhost:8200"
    silent: true

  down:
    cmds:
      - task: stop

  restart:
    cmds:
      - docker compose restart vault

  status:
    cmds:
      - vault status

  init:
    cmds:
      - ./scripts/10_vault_init.sh

  unseal:
    cmds:
      - ./scripts/20_vault_unseal.sh
      - vault token renew $(cat ./volumes/prometheus/prometheus-token)
      - docker compose restart prometheus

  backup:
    cmds:
      - echo $VAULT_CACERT
      - vault operator raft snapshot save backup-`date +"%Y%m%d-%H%M"`.snap

  rm:
    aliases: ["clean"]
    cmds:
      - docker compose rm -sfv
      - docker volume rm {{.STACK_NAME }}_grafana-data
      - docker volume rm {{.STACK_NAME }}_loki-data
      - docker volume rm {{.STACK_NAME }}_prometheus-data
      - docker volume rm {{.STACK_NAME }}_promtail-data
      - docker volume rm {{.STACK_NAME }}_vault-data
      - docker volume rm {{.STACK_NAME }}_vault-logs
    ignore_error: true
    vars:
      STACK_NAME:
        sh: basename "`pwd`"

  benchmark:
    cmds:
      - vault-benchmark run -config=./benchmark/config.hcl

  metrics:
      cmds:
        - |
          curl -s --header "X-Vault-Token: $VAULT_TOKEN" "$VAULT_ADDR/v1/sys/metrics?format=prometheus"
          
  logs-vault:
    cmds:
      - docker compose logs -f --tail=100 vault

  logs:
    cmds:
      - docker compose logs -f

  stop:
    cmds:
      - docker compose stop

  agent-up:
    dir: ./tfc-agent
    preconditions:
      - test -f .env
      - test -f docker-compose.yml
    cmds:
      - docker compose up -d --pull=missing

  agent-down:
    dir: ./tfc-agent
    preconditions:
      - test -f .env
      - test -f docker-compose.yml
    cmds:
      - docker compose stop

  ui:
    cmds:
      - open https://localhost:8200
      - ./scripts/00_vault_vars.sh

  pull:
    cmds:
      - docker compose pull
    silent: true

  dev:
    preconditions:
      - test -f .env
    cmds:
      - docker run --rm -p 8200:8200 --cap-add=IPC_LOCK -e VAULT_LICENSE=$VAULT_LICENSE hashicorp/vault-enterprise:latest server -dev -dev-root-token-id=root -dev-listen-address="0.0.0.0:8200"
    silent: true


  config:
    cmds:
      - ./scripts/30_vault_config.sh
      - docker compose restart prometheus

  shell:
    cmds:
      - docker exec -it {{.STACK_NAME }}_vault /bin/sh
    vars:
      STACK_NAME:
        sh: basename "`pwd`"