{
 "title": "Vault / Tokens",
 "description": "Vault token creation, counts and TTLs by namespace and auth method (Prometheus)",
 "tags": [
  "vault",
  "tokens",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(vault_core_active,job)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(vault_core_active{job=~\"$job\"},cluster)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(vault_core_active{job=~\"$job\", cluster=\"$cluster\"},instance)"
    }
   },
   {
    "name": "quantile",
    "label": "Quantile",
    "query": {
     "query": "label_values(vault_token_create{job=~\"$job\", cluster=\"$cluster\"},quantile)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(vault_token_creation{job=~\"$job\", cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "auth_method",
    "label": "Auth Method",
    "query": {
     "query": "label_values(vault_token_creation{job=~\"$job\", cluster=\"$cluster\", namespace=~\"$namespace\"},auth_method)"
    }
   },
   {
    "name": "creation_ttl",
    "label": "Creation TTL",
    "query": {
     "query": "label_values(vault_token_creation{job=~\"$job\", cluster=\"$cluster\", namespace=~\"$namespace\"},creation_ttl)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tokens Count",
   "type": "stat",
   "description": "Number of un-expired and un-revoked tokens available for use in the token store.<br/>\n\nReported by the active (leader) node only.<br/>\n\nPeriodic usage gauge (emitted every 10 minutes by default), so it can lag or be empty right after startup.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vault_token_count{job=~\"$job\",cluster=~\"$cluster\"} and on(instance) (vault_core_active == 1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Token creation",
   "type": "stat",
   "description": "Tokens created per second across all namespaces and auth methods.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(vault_token_creation{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tokens created",
   "type": "stat",
   "description": "Tokens created during the selected time range.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(vault_token_creation{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Token Creation (Rate) - ${auth_method}",
   "type": "timeseries",
   "description": "Tokens created per second by token type.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(token_type) (irate(vault_token_creation{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Token Creation (Duration)",
   "type": "timeseries",
   "description": "Time required to create a token in Vault",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vault_token_create{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",quantile=~\"$quantile\"}",
     "legendFormat": "{{instance}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Token Create Accessor (Duration)",
   "type": "timeseries",
   "description": "Time required to create a token accessor in Vault.<br/>\n\nReported by the active (leader) node only.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vault_token_createAccessor{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",quantile=~\"$quantile\"}",
     "legendFormat": "{{instance}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Token Lookup (Duration)",
   "type": "timeseries",
   "description": "Time required to look up a token in Vault.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vault_token_lookup{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",quantile=~\"$quantile\"}",
     "legendFormat": "{{instance}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Token Revocation (Duration)",
   "type": "timeseries",
   "description": "Time required to revoke a token in Vault",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vault_expire_revoke{job=~\"$job\",cluster=~\"$cluster\",quantile=~\"$quantile\"}",
     "legendFormat": "{{instance}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Token Revocation Tree (Duration)",
   "type": "timeseries",
   "description": "Time required to fully revoke a token tree in Vault.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vault_token_revoke_tree{job=~\"$job\",cluster=~\"$cluster\",quantile=~\"$quantile\"}",
     "legendFormat": "{{instance}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Namespace - $namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "repeat": "namespace",
   "collapsed": true,
   "panels": [
    {
     "title": "Tokens Count",
     "type": "stat",
     "description": "Number of un-expired and un-revoked tokens available for use in the token store.<br/>\n\nReported by the active (leader) node only.<br/>\n\nPeriodic usage gauge (emitted every 10 minutes by default), so it can lag or be empty right after startup.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(vault_token_count{job=~\"$job\",cluster=~\"$cluster\",namespace=~\"$namespace\"} and on(instance) (vault_core_active == 1))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Token Creation (Rate) - Auth Method: ${auth_method}",
     "type": "timeseries",
     "description": "Tokens created per second by auth method.",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 31 },
     "repeat": "auth_method",
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by(mount_point,token_type) (irate(vault_token_creation{\n  job=~\"$job\",\n  cluster=~\"$cluster\",\n  namespace=~\"$namespace\",\n  auth_method=~\"$auth_method\",\n  creation_ttl=~\"$creation_ttl\"}[$__rate_interval])\n)",
       "legendFormat": "{{token_type}} - {{mount_point}}"
      }
     ]
    }
   ]
  }
 ]
}