{
 "title": "Vault / Integrated Storage",
 "description": "Raft integrated storage: leadership, commits, FSM, RPC and storage operations (Prometheus)",
 "tags": [
  "vault",
  "raft",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(vault_core_active,job)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(vault_core_active{job=~\"$job\"},cluster)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(vault_core_active{job=~\"$job\",cluster=\"$cluster\"},instance)"
    }
   },
   {
    "name": "quantile",
    "label": "Quantile",
    "query": {
     "query": "label_values(vault_barrier_get{job=~\"$job\", cluster=\"$cluster\"},quantile)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Raft peers",
   "type": "stat",
   "description": "Voters and non-voters in the Raft configuration.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(vault_raft_peers{job=~\"$job\",cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failure tolerance",
   "type": "stat",
   "description": "Voter nodes that can fail before losing quorum (autopilot).",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(vault_autopilot_failure_tolerance{job=~\"$job\",cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Autopilot",
   "type": "stat",
   "description": "Overall cluster health from autopilot.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(vault_autopilot_healthy{job=~\"$job\",cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commit time p99",
   "type": "stat",
   "description": "99th percentile time to commit a Raft log entry on the leader.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(vault_raft_commitTime{job=~\"$job\",cluster=~\"$cluster\",quantile=\"0.99\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FSM size",
   "type": "stat",
   "description": "BoltDB pages allocated for the FSM (vault.db).",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vault_raft_storage_bolt_page_bytes_allocated{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",database=\"fsm\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log store size",
   "type": "stat",
   "description": "BoltDB pages allocated for the Raft log store (raft.db).",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vault_raft_storage_bolt_page_bytes_allocated{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",database=\"logstore\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Caching (Rate)",
   "type": "timeseries",
   "description": "Activity of Least Recently Used (LRU) cache in front of storage backend.<br/>\n\nIMPORTANT: Panel will reflect instance variable value(s).",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(irate(vault_cache_miss{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "MISS"
    },
    {
     "expr": "sum(irate(vault_cache_write{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "WRITE"
    },
    {
     "expr": "sum(irate(vault_cache_hit{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "HIT"
    },
    {
     "expr": "sum(irate(vault_cache_delete{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "DELETE"
    }
   ]
  },
  { "title": "Log Replication & Commits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "RPC Append Entries (Rate)",
   "type": "timeseries",
   "description": "Rate of RPC appendEntries received from leader node.<br/>\n\nIMPORTANT: Panel will reflect instance variable value(s).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(vault_raft_rpc_appendEntries_count{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval]) and on(instance) (vault_core_active == 0))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RPC Append Entries (Duration)",
   "type": "timeseries",
   "description": "Time required to process a remote appendEntries call from a node.<br/>\n\nIMPORTANT: Panel will reflect instance variable value(s).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vault_raft_rpc_appendEntries{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",quantile=~\"$quantile\"}",
     "legendFormat": "{{instance}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Raft Commit (Rate)",
   "type": "timeseries",
   "description": "Commits to the raft log on the leader node.<br/>\n\nIMPORTANT: Panel will reflect instance variable value(s).<br/>\n\nReported by the active (leader) node only.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(vault_raft_commitTime_count{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval]) and on(instance) (vault_core_active == 1)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Raft Commit (Duration)",
   "type": "timeseries",
   "description": "Time required to commit a new entry to the raft log on the leader node.<br/>\n\nIMPORTANT: Panel will reflect instance variable value(s).<br/>\n\nReported by the active (leader) node only.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vault_raft_commitTime{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",quantile=~\"$quantile\"}",
     "legendFormat": "{{instance}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Raft Transaction (Rate)",
   "type": "timeseries",
   "description": "Activity of transactions operations.<br/>\n\nIMPORTANT: Panel will reflect instance variable value(s).<br/>\n\nReported by the active (leader) node only.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(vault_raft_storage_transaction_count{job=~\"$job\", cluster=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval]) and on(instance) (vault_core_active == 1)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Raft Transaction (Duration)",
   "type": "timeseries",
   "description": "Time required to insert raft operations into a single log.<br/>\n\nIMPORTANT: Panel will reflect instance variable value(s).<br/>\n\nReported by the active (leader) node only.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vault_raft_storage_transaction{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",quantile=~\"$quantile\"}",
     "legendFormat": "{{instance}} - {{quantile}}"
    }
   ]
  },
  { "title": "Storage Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Raft PUT (Duration)",
   "type": "timeseries",
   "description": "Time required to insert a log entry to the persist path.<br/>\n\nIMPORTANT: Panel will reflect instance variable value(s).<br/>\n\nReported by the active (leader) node only.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "# leader only\nvault_raft_storage_put{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",quantile=~\"$quantile\"}",
     "legendFormat": "{{instance}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Raft DELETE (Duration)",
   "type": "timeseries",
   "description": "Time required to insert log entry to delete path.<br/>\n\nIMPORTANT: Panel will reflect instance variable value(s).<br/>\n\nReported by the active (leader) node only.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "# leader only\nvault_raft_storage_delete{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",quantile=~\"$quantile\"}",
     "legendFormat": "{{instance}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Raft GET (Duration)",
   "type": "timeseries",
   "description": "Time required to retrieve a value for the given path from the finite state machine.<br/>\n\nIMPORTANT: Panel will reflect instance variable value(s).",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vault_raft_storage_get{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",quantile=~\"$quantile\"}",
     "legendFormat": "{{instance}} -  {{quantile}}"
    }
   ]
  },
  {
   "title": "Raft LIST (Duration)",
   "type": "timeseries",
   "description": "Time required to list all entries under the prefix from the finite state machine.<br/>\n\nIMPORTANT: Panel will reflect instance variable value(s).",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vault_raft_storage_list{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",quantile=~\"$quantile\"}",
     "legendFormat": "{{instance}} - {{quantile}}"
    }
   ]
  },
  { "title": "Finite State Machine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "FSM Enqueue (Duration)",
   "type": "timeseries",
   "description": "Time required to queue up a batch of logs for the finite state machine to apply.<br/>\n\nReported by the active (leader) node only.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vault_raft_fsm_enqueue{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",quantile=~\"$quantile\"}",
     "legendFormat": "{{instance}} -  {{quantile}}"
    }
   ]
  },
  {
   "title": "FSM Apply (Duration)",
   "type": "timeseries",
   "description": "Time required to apply the log(s) to the finite state machine.<br/>\n\nIMPORTANT: Panel will reflect instance variable value(s).",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vault_raft_fsm_applyBatch{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",quantile=~\"$quantile\"}",
     "legendFormat": "{{instance}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "FSM Snapshot (Duration)",
   "type": "timeseries",
   "description": "Time required by the finite state machine to record state information for the current snapshot.<br/>\n\nIMPORTANT: Panel will reflect instance variable value(s).",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vault_raft_fsm_snapshot{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",quantile=~\"$quantile\"}",
     "legendFormat": "{{instance}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "FSM Restore (Duration)",
   "type": "timeseries",
   "description": "Time required by the finite state machine to complete a restore operation from a snapshot.<br/>\n\nIMPORTANT: Panel will reflect instance variable value(s).",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vault_raft_fsm_restore{job=~\"$job\",cluster=~\"$cluster\",instance=~\"$instance\",quantile=~\"$quantile\"}",
     "legendFormat": "{{instance}} - {{quantile}}"
    }
   ]
  }
 ]
}