scrape_configs:
  - job_name: vault
    metrics_path: /v1/sys/metrics
    params:
      format: ['prometheus']
    scheme: https
    bearer_token_file: /etc/prometheus/prometheus-token
    static_configs:
    - targets: ['vault:8200']
    tls_config:
      insecure_skip_verify: true

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
