# https://taskfile.dev

version: '3'

env:
  AWS_PAGER: ""

tasks:

  prereqs:
    desc: check and create admin/tn001 namespace if it doesn't exist
    preconditions:
      - sh: vault status
        msg: "Vault is not running or unsealed. Run 'task up' and 'task unseal' first."
    cmds:
      - |
        echo "Checking for admin namespace..."
        if ! vault namespace list -format=json | jq -e '.[] | select(. == "admin/")' > /dev/null 2>&1; then
          echo "Creating admin namespace..."
          vault namespace create admin
        fi
      - |
        echo "Checking for admin/tn001 namespace..."
        if ! vault namespace list -namespace=admin -format=json | jq -e '.[] | select(. == "tn001/")' > /dev/null 2>&1; then
          echo "Creating tn001 namespace under admin..."
          vault namespace create -namespace=admin tn001
        fi
        echo ""
        echo "Namespace check complete. admin/tn001 is ready for use."
    silent: true

  init:
    desc: initialize terraform
    preconditions:
      - sh: vault status
        msg: "Vault is not running or unsealed"
    cmds:
      - terraform init

  plan:
    desc: plan terraform changes
    preconditions:
      - sh: vault status
        msg: "Vault is not running or unsealed"
      - sh: test -f .terraform.lock.hcl
        msg: "Terraform not initialized. Run 'task init' first"
    cmds:
      - terraform plan

  apply:
    desc: apply terraform configuration
    preconditions:
      - sh: vault status
        msg: "Vault is not running or unsealed"
      - sh: test -f .terraform.lock.hcl
        msg: "Terraform not initialized. Run 'task init' first"
    cmds:
      - terraform apply -auto-approve

  output:
    desc: show terraform outputs
    cmds:
      - terraform output

  verify-sync:
    desc: check secrets sync destination associations status
    preconditions:
      - sh: vault status
        msg: "Vault is not running or unsealed"
    cmds:
      - |
        DEST_NAME=$(terraform output -json 2>/dev/null | jq -r '.sync_destination_name.value // "aws-sm-eu-west-1"')
        DEST_TYPE=$(terraform output -json 2>/dev/null | jq -r '.sync_destination_type.value // "aws-sm"')
        NAMESPACE=$(terraform output -json 2>/dev/null | jq -r '.namespace_path.value // "admin/tn001"')

        if [ -z "$DEST_NAME" ] || [ -z "$DEST_TYPE" ] || [ -z "$NAMESPACE" ]; then
          echo "⚠ Unable to get sync destination details from terraform outputs."
          echo "Run 'task apply' first to create the sync destination."
          exit 1
        fi

        echo "=== Checking Sync Destination Associations ==="
        echo ""
        echo "Destination: $DEST_TYPE/$DEST_NAME"
        echo "Namespace: $NAMESPACE"
        echo ""

        JSON=$(vault read -namespace=$NAMESPACE -format=json sys/sync/destinations/$DEST_TYPE/$DEST_NAME/associations)
        echo "$JSON" | jq

        echo ""
        COUNT=$(echo "$JSON" | jq -r '.data.associated_secrets // {} | to_entries | length')
        SYNCED_COUNT=$(echo "$JSON" | jq -r '[.data.associated_secrets // {} | to_entries[] | select(.value.sync_status == "SYNCED")] | length')
        echo "Synced: $SYNCED_COUNT"
        echo "Total: $COUNT"

    silent: true

  cleanup-sync-destination:
    desc: delete vault sync destination with purge (removes all associations)
    preconditions:
      - sh: vault status
        msg: "Vault is not running or unsealed"
    cmds:
      - |
        DEST_NAME=$(terraform output -json 2>/dev/null | jq -r '.sync_destination_name.value // "aws-sm-eu-west-1"')
        DEST_TYPE=$(terraform output -json 2>/dev/null | jq -r '.sync_destination_type.value // "aws-sm"')
        NAMESPACE=$(terraform output -json 2>/dev/null | jq -r '.namespace_path.value // "admin/tn001"')

        if [ -z "$DEST_NAME" ] || [ -z "$DEST_TYPE" ] || [ -z "$NAMESPACE" ]; then
          echo "⚠ Unable to get sync destination details from terraform outputs."
          echo "Sync destination may already be deleted or terraform has not been applied."
          exit 0
        fi

        echo "=== Cleaning Up Sync Destination ==="
        echo ""
        echo "Destination: $DEST_TYPE/$DEST_NAME"
        echo "Namespace: $NAMESPACE"
        echo ""

        # Check current associations
        echo "Checking current associations..."
        COUNT=$(vault read -namespace=$NAMESPACE -format=json sys/sync/destinations/$DEST_TYPE/$DEST_NAME/associations 2>/dev/null | jq -r '.data.associated_secrets // {} | to_entries | length')
        if [ -z "$COUNT" ] || [ "$COUNT" = "null" ]; then
          COUNT=0
        fi
        echo "Found $COUNT association(s)"
        echo ""

        # If no associations found, sync destination likely already deleted
        if [ "$COUNT" -eq 0 ]; then
          echo "✓ Sync destination already removed or does not exist"
          exit 0
        fi

        # Delete sync destination using Vault API with purge=true
        # https://developer.hashicorp.com/vault/api-docs/system/secrets-sync#delete-destination
        echo "Deleting sync destination with purge=true (forces removal of all associations)..."

        HTTP_CODE=$(curl -sk -X DELETE \
          -H "X-Vault-Token: $VAULT_TOKEN" \
          -H "X-Vault-Namespace: $NAMESPACE" \
          -w "%{http_code}" \
          -o /dev/null \
          "$VAULT_ADDR/v1/sys/sync/destinations/$DEST_TYPE/$DEST_NAME?purge=true")

        if [ "$HTTP_CODE" = "204" ] || [ "$HTTP_CODE" = "200" ]; then
          echo "✓ Sync destination deleted successfully"
        elif [ "$HTTP_CODE" = "404" ]; then
          echo "⚠ Sync destination not found (may already be deleted)"
        else
          echo "⚠ Unexpected response code: $HTTP_CODE"
        fi
        echo ""

        # Verify associations are removed
        echo "Verifying sync associations have been removed..."
        vault read -namespace=$NAMESPACE -format=json sys/sync/destinations/$DEST_TYPE/$DEST_NAME/associations 2>/dev/null || VERIFY_EXIT=$?
        if [ "${VERIFY_EXIT:-0}" -ne 0 ]; then
          echo "✓ Sync destination and associations removed"
        else
          echo "⚠ Sync destination may still exist"
        fi

        # Remove sync association from terraform state
        echo ""
        echo "Removing sync associations from Terraform state..."
        terraform state rm 'vault_secrets_sync_association.test_secrets' 2>/dev/null || true
        echo "✓ State cleanup complete"
    silent: true

  destroy:
    desc: destroy terraform resources and cleanup sync associations
    preconditions:
      - sh: vault status
        msg: "Vault is not running or unsealed"
    cmds:
      - terraform destroy -auto-approve

  verify-aws:
    desc: verify aws secrets have been created
    preconditions:
      - sh: command -v aws
        msg: "AWS CLI not found. Install it: https://aws.amazon.com/cli/"
      - sh: aws sts get-caller-identity > /dev/null 2>&1
        msg: "AWS credentials not configured. Set AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY"
    cmds:
      - |
        echo "=== Verifying AWS Secrets Manager Secrets ==="
        echo ""
        echo "Listing Vault-managed secrets in AWS Secrets Manager:"
        aws secretsmanager list-secrets \
          --region ${AWS_REGION:-eu-west-1} \
          --filters Key=tag-key,Values=ManagedBy Key=tag-value,Values=Vault \
          --query 'SecretList[*].[Name,ARN,CreatedDate]' \
          --output table
        echo ""
        echo "Total count:"
        aws secretsmanager list-secrets \
          --region ${AWS_REGION:-eu-west-1} \
          --filters Key=tag-key,Values=ManagedBy Key=tag-value,Values=Vault \
          --query 'length(SecretList)' \
          --output text
        echo ""
        echo "To get a specific secret value, use:"
        echo "  aws secretsmanager get-secret-value --region ${AWS_REGION:-eu-west-1} --secret-id <secret-name> --query SecretString --output text"
    silent: true

  cleanup-aws:
    desc: cleanup aws secrets manager secrets created by vault sync
    preconditions:
      - sh: command -v aws
        msg: "AWS CLI not found. Install it: https://aws.amazon.com/cli/"
      - sh: aws sts get-caller-identity > /dev/null 2>&1
        msg: "AWS credentials not configured. Set AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY"
    cmds:
      - |
        echo "=== Cleaning up AWS Secrets Manager Secrets ==="
        echo ""
        echo "Finding Vault-managed secrets..."
        SECRET_ARNS=$(aws secretsmanager list-secrets \
          --region ${AWS_REGION:-eu-west-1} \
          --filters Key=tag-key,Values=ManagedBy Key=tag-value,Values=Vault \
          --query 'SecretList[*].ARN' \
          --output text)

        if [ -z "$SECRET_ARNS" ]; then
          echo "No Vault-managed secrets found in AWS Secrets Manager."
          exit 0
        fi

        echo "Found secrets to delete:"
        for arn in $SECRET_ARNS; do
          secret_name=$(echo $arn | rev | cut -d: -f1 | rev)
          echo "  - $secret_name"
        done
        echo ""

        # Skip prompt if SKIP_PROMPT is set (used by destroy task)
        if [ "${SKIP_PROMPT}" != "true" ]; then
          echo "WARNING: This will permanently delete all Vault-managed secrets from AWS Secrets Manager!"
          echo "Press Ctrl+C to cancel, or press Enter to continue..."
          read
          echo ""
        fi

        echo "Deleting secrets..."
        for arn in $SECRET_ARNS; do
          secret_name=$(echo $arn | rev | cut -d: -f1 | rev)
          echo "Deleting: $secret_name"
          aws secretsmanager delete-secret \
            --region ${AWS_REGION:-eu-west-1} \
            --secret-id "$arn" \
            --force-delete-without-recovery 2>/dev/null || echo "  ⚠ Failed to delete (may already be deleted)"
        done

        echo ""
        echo "Cleanup complete. Verifying remaining secrets:"
        REMAINING=$(aws secretsmanager list-secrets \
          --region ${AWS_REGION:-eu-west-1} \
          --filters Key=tag-key,Values=ManagedBy Key=tag-value,Values=Vault \
          --query 'length(SecretList)' \
          --output text)
        echo "Remaining Vault-managed secrets: $REMAINING"
    silent: true

  all:
    desc: complete setup for aws secrets sync lab
    cmds:
      - task: prereqs
      - task: init
      - task: plan
      - task: apply
      - echo ""
      - echo "View synced secrets:"
      - task: output
      - echo ""
      - echo "Verify secrets in AWS:"
      - task: verify-aws
      - echo ""

  secrets:update:
    desc: refresh aws secrets to see sync in action
    cmds:
      - |
        echo "Replacing secrets in Vault to trigger AWS sync..."
        SECRET_PATHS=(
          "kv-sync/app1_secrets"
          "kv-sync/app2_secrets"
        )
        for path in "${SECRET_PATHS[@]}"; do
          echo "Updating secret at: $path"
          vault kv put -namespace=admin/tn001 "$path" username="user_$(date +%s)" password="pass_$(date +%s)"
        done
        echo "Secrets updated. AWS Secrets Manager will reflect changes shortly."

  secrets:refresh:
    desc: refresh aws secrets to see sync in action
    cmds:
      - echo "Refreshing sync associations to trigger AWS sync..."
      - terraform apply -replace='vault_secrets_sync_association.test_secrets' -auto-approve
      - task: verify-aws
      - task: verify-sync

